# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xray/app/proxyman/command/command.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'xray/app/proxyman/command/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xray.common.serial import typed_message_pb2 as xray_dot_common_dot_serial_dot_typed__message__pb2
from xray.common.protocol import user_pb2 as xray_dot_common_dot_protocol_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'xray/app/proxyman/command/command.proto\x12\x19xray.app.proxyman.command\x1a&xray/common/serial/typed_message.proto\x1a\x1fxray/common/protocol/user.proto\"<\n\x10\x41\x64\x64UserOperation\x12(\n\x04user\x18\x01 \x01(\x0b\x32\x1a.xray.common.protocol.User\"$\n\x13RemoveUserOperation\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"W\n\x13\x41lterInboundRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x33\n\toperation\x18\x02 \x01(\x0b\x32 .xray.common.serial.TypedMessage\"\x16\n\x14\x41lterInboundResponse2\x81\x01\n\x0eHandlerService\x12o\n\x0c\x41lterInbound\x12..xray.app.proxyman.command.AlterInboundRequest\x1a/.xray.app.proxyman.command.AlterInboundResponseB0Z.github.com/xtls/xray-core/app/proxyman/commandb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xray.app.proxyman.command.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/xtls/xray-core/app/proxyman/command'
  _globals['_ADDUSEROPERATION']._serialized_start=143
  _globals['_ADDUSEROPERATION']._serialized_end=203
  _globals['_REMOVEUSEROPERATION']._serialized_start=205
  _globals['_REMOVEUSEROPERATION']._serialized_end=241
  _globals['_ALTERINBOUNDREQUEST']._serialized_start=243
  _globals['_ALTERINBOUNDREQUEST']._serialized_end=330
  _globals['_ALTERINBOUNDRESPONSE']._serialized_start=332
  _globals['_ALTERINBOUNDRESPONSE']._serialized_end=354
  _globals['_HANDLERSERVICE']._serialized_start=357
  _globals['_HANDLERSERVICE']._serialized_end=486
# @@protoc_insertion_point(module_scope)
